### ISSUE TITLE
there is no `load` method in `SpacyModelManager`

### ISSUE THREAD

**Issue by iulusoy** [ssciwr/moralization#90]

**Comment by lkeegan** [comment]
The idea was to load a model by instantiating a `ModelManager` object with a `model_path` that points to an existing model - then each `ModelManager` object always refers to the same model, and to load a different model you would create a new `ModelManager` object.

But I'm fine with adding an explicit `load` method if you prefer that.

**Comment by iulusoy** [comment]
Re: 

> General api question: should a ModelManager instance only offer methods to modify its model, or should these methods also have a model argument where they can modify another model?
> 
> e.g. is load_model in TransformersModelManager required, or could this functionality be part of the init of the object where the model is specified?

For modifying a model, we have two models that we access: The original model that is being modified, ie retrained, and the model that is generated through the training.
The `_load_model` method loads the model that will be trained. In spacy, this is done inherently.
But one could also envision the use case that a trained model will be loaded and tested; possibly on a different task that it was trained for. To see how well it performs for the unknown task and which one should be retrained for it. 

In this case, the model will not be modified. There is only one model that needs to be loaded.

For transformers, this is easy to do as we need to load a model in any case, so this can be done in the init. For spacy, it is not so clear. Can you just test any model in spacy and get accuracy measures for it? Or does it need to be done in/just after the training?

**Comment by lkeegan** [comment]
`SpacyModelManager` saves the original cfg file that defines the model and (after training) also the "last" and "best" trained models.
So if you load an existing trained model (as in the last cell of the example notebook) you can then do
```
loaded_model.test("Das Wetter ist schön")
```
and it will use the saved "best" trained model.

So (as far as I can see) this should also be fine for `SpacyModelManager`
